# Generated by Django 2.2 on 2020-11-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20201109_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.CharField(default='', max_length=255),
        ),
    ]
